plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.visionocr'
version = '0.0.1'

android {
  namespace "expo.modules.visionocr"
  defaultConfig { versionCode 1; versionName "0.0.1" }
}

dependencies {
  implementation 'com.google.mlkit:text-recognition:16.0.1'
  implementation 'androidx.exifinterface:exifinterface:1.4.2'
}
